name: Demo Deploy

on:
  push:
    branches: [ 'master' ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    - name: Install deps
      run: |
        cd demo && yarn install --frozen-lockfile --ignore-scripts

    - name: Build and export
      run: |
        cd demo && yarn build && yarn export && touch out/.nojekyll

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: demo/out # The folder the action should deploy.
